---

- hosts: m25-cassandra
  remote_user: ubuntu
  sudo: yes
  vars:
    cluster_name: Test Cluster
    seeds: 10.79.134.220

  tasks:
  - name: install htop
    apt: name=htop state=present

  roles:
    - cassandra
    - opscenter
    - spark
