---

- hosts: m25-cassandra
  remote_user: ubuntu
  sudo: yes
  vars:
    cluster_name: Test Cluster
    seeds: 10.79.134.173

  tasks:
  - name: install htop
    apt: name=htop state=present

  - name: install java
    apt: name=openjdk-7-jre state=present update_cache=yes

  roles:
    - cassandra
    - opscenter
    - spark
