- name: install htop
  apt: name=htop state=present

- name: install java
  apt: name=openjdk-7-jre state=present update_cache=yes

- name: download spark
  get_url: url=http://d3kbcqa49mib13.cloudfront.net/spark-1.0.0-bin-hadoop2.tgz dest=/opt/

- name: unzip spark
  unarchive: copy=no src=/opt/spark-1.0.0-bin-hadoop2.tgz  dest=/opt
